### ISSUE TITLE
Course data is not being updated

### ISSUE THREAD

**Issue by bvenkatr** [overhangio/tutor-figures#2]
Hi, I have enabled figures  plugin in my tutor instance, and when I went to the **localhost/figures** on browser, then it is not showing number of  registered users and and course enrollments and so on. Looks like there might be some issue gathering these stattics.

I have 2 courses, 2 users and users were enrolled in those courses as well.

we have a discussion in openedx tutor slack channel, here is link for that,
https://openedx.slack.com/archives/CGE253B7V/p1587992449003900

![image](https://user-images.githubusercontent.com/6078345/80449114-e4079780-893b-11ea-8758-e1f5c458b655.png)

The log of **figures-populate-daily-metrics**
`tutor local logs | grep -C 50 "figures-populate-daily-metrics"`

`cms_1              | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
cms_1              |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
cms_1              |
cms_1              | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
cms-worker_1       | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
cms-worker_1       |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
cms-worker_1       |
cms-worker_1       | 2020-04-27 02:05:30,047 WARNING 1 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
cms-worker_1       | 2020-04-27 02:05:30,054 WARNING 1 [enterprise.utils] utils.py:51 - cannot import name EnterpriseCustomerUser
cms-worker_1       | 2020-04-27 02:06:17,986 WARNING 1 [py.warnings] platforms.py:812 - /openedx/venv/local/lib/python2.7/site-packages/celery/platforms.py:812: RuntimeWarning: You are running the worker with superuser privileges, which is
cms-worker_1       | absolutely not recommended!
cms-worker_1       |
cms-worker_1       | Please specify a different user using the -u option.
cms-worker_1       |
cms-worker_1       | User information: uid=0 euid=0 gid=0 egid=0
cms-worker_1       |
cms-worker_1       |   uid=uid, euid=euid, gid=gid, egid=egid,
cms-worker_1       |
cms-worker_1       | [2020-04-27 02:06:18,216: WARNING/MainProcess] /openedx/venv/local/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning:
cms-worker_1       | Starting from version 3.2 Celery will refuse to accept pickle by default.
cms-worker_1       |
cms-worker_1       | The pickle serializer is a security concern as it may give attackers
cms-worker_1       | the ability to execute any command.  It's important to secure
cms-worker_1       | your broker from unauthorized access when using pickle, so we think
cms-worker_1       | that enabling pickle should require a deliberate action and not be
cms-worker_1       | the default choice.
cms-worker_1       |
cms-worker_1       | If you depend on pickle then you should set a setting to disable this
cms-worker_1       | warning and to be sure that everything will continue working
cms-worker_1       | when you upgrade to Celery 3.2::
cms-worker_1       |
cms-worker_1       |     CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
cms-worker_1       |
cms-worker_1       | You must only enable the serializers that you will actually use.
cms-worker_1       |
cms-worker_1       |
cms-worker_1       |   warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))
cms-worker_1       |
cms-worker_1       |
cms-worker_1       |  -------------- celery@edx.cms.core.default.%56d63f8cdf0f v3.1.25 (Cipater)
lms_worker_beat_1  | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
lms_worker_beat_1  |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
lms_worker_beat_1  |
lms_worker_beat_1  | 2020-04-27 02:05:32,081 WARNING 1 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
lms_worker_beat_1  | 2020-04-27 02:05:32,088 WARNING 1 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
lms_worker_beat_1  | 2020-04-27 02:06:23,235 INFO 1 [celery.beat] beat.py:468 - beat: Starting...
lms_worker_beat_1  | 2020-04-27 02:06:23,515 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
lms_worker_beat_1  | 2020-04-27 02:06:25,594 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 4.0 seconds...
lms_worker_beat_1  | 2020-04-27 02:06:29,649 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 6.0 seconds...
lms_worker_beat_1  | 2020-04-27 02:06:35,675 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 8.0 seconds...
lms_worker_beat_1  | 2020-04-27 06:00:00,002 INFO 1 [celery.beat] beat.py:202 - Scheduler: Sending due task figures-populate-daily-metrics (figures.tasks.populate_daily_metrics)
lms_worker_beat_1  | 2020-04-27 08:00:00,004 INFO 1 [celery.beat] beat.py:202 - Scheduler: Sending due task celery.backend_cleanup (celery.backend_cleanup)
elasticsearch_1    | [2020-04-27 02:29:53,243][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:30:23,058][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:30:53,040][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:31:23,133][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:31:23,133][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:31:53,125][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:32:23,067][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:32:53,094][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:32:53,094][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:33:23,113][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:33:53,100][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:33:53,100][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:34:23,147][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:34:53,102][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:34:53,102][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:35:23,102][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:35:53,072][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:36:23,261][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:36:23,261][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:36:53,083][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:37:23,102][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:37:53,083][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:37:53,084][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:38:23,123][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:38:53,104][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:38:53,104][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:39:23,130][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:39:53,109][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:39:53,110][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:40:23,143][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:40:53,446][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:40:53,447][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:41:23,102][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:41:53,128][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:42:23,132][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:42:23,133][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
elasticsearch_1    | [2020-04-27 02:42:53,116][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:43:23,104][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:43:53,117][WARN ][cluster.routing.allocation.decider] [Strobe] high disk watermark [10%] exceeded on [Z6dOIsXiQ4WKXORsERGG3w][Strobe] free: 11.3gb[4.8%], shards will be relocated away from this node
elasticsearch_1    | [2020-04-27 02:43:53,117][INFO ][cluster.routing.allocation.decider] [Strobe] high disk watermark exceeded on one or more nodes, rerouting shards
cms_1              |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
cms_1              |
cms_1              | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
cms_1              |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
cms_1              |
cms_1              | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
cms_1              |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
cms_1              |
cms_1              | 2020-04-27 02:07:09,717 WARNING 235 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
`

**Comment by regisb** [comment]
Dear @bvenkatr,
I am currently investigating this. Can you please paste here the output of `tutor local logs lms-worker-beat`?

**Comment by bvenkatr** [comment]
Hi, sorry for the late. here is the output
```
IL1019:~ user1$ tutor local logs lms-worker-beat
docker-compose -f /Users/user1/tutor-data/env/local/docker-compose.yml --project-name tutor_local logs lms-worker-beat
Attaching to tutor_local_lms-worker-beat_1
lms-worker-beat_1  | WARNING:py.warnings:/openedx/edx-platform/lms/djangoapps/courseware/__init__.py:5: DeprecationWarning: Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported
lms-worker-beat_1  |   warnings.warn("Importing 'lms.djangoapps.courseware' as 'courseware' is no longer supported", DeprecationWarning)
lms-worker-beat_1  |
lms-worker-beat_1  | 2020-06-12 08:50:01,605 WARNING 1 [enterprise.utils] utils.py:50 - Could not import Registry from third_party_auth.provider
lms-worker-beat_1  | 2020-06-12 08:50:01,613 WARNING 1 [enterprise.utils] utils.py:51 - cannot import name _LTI_BACKENDS
lms-worker-beat_1  | 2020-06-12 08:50:59,450 INFO 1 [celery.beat] beat.py:468 - beat: Starting...
lms-worker-beat_1  | 2020-06-12 08:50:59,877 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 2.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:02,163 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 4.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:06,256 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 6.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:12,357 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 8.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:20,443 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 10.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:30,557 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 12.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:42,658 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 14.0 seconds...
lms-worker-beat_1  | 2020-06-12 08:51:56,790 ERROR 1 [celery.beat] beat.py:324 - beat: Connection error: [Errno 111] Connection refused. Trying again in 16.0 seconds...
```

**Comment by bvenkatr** [comment]
@regisb

**Comment by regisb** [comment]
According to my experience, this is resolved in the latest release. Please upgrade the plugin to 0.2.3 and run `tutor local quickstart`. If this does not resolve your problem, please reopen this issue.

Note that the figures plugin is not yet compatible with tutor v10. DO NOT upgrade tutor to the latest release if you want to keep using figures.

**Comment by sajidghufran** [comment]
Hi @regisb. I am facing same issue. We had installed tutor from binary. Can you please tell me how to upgrade figure plugin to 0.2.3. I have currently tutor, version 3.11.12 installed and version of figures plugin is 0.1.1.
