### ISSUE TITLE
Juniper support

### ISSUE THREAD

**Issue by tuanh118** [overhangio/tutor-figures#3]
Hello,

We saw this commit https://github.com/overhangio/tutor-figures/commit/f039d43268730df857dac88c0d11069faff7c90e enforcing Ironwood release for this plugin. Why is this the case? Do we have plans to support it in Juniper?

Thank you!

**Comment by regisb** [comment]
Figures is currently not compatible with Juniper. As a consequence, this plugin cannot be made compatible with Juniper either. (yet)
