### ISSUE TITLE
Facing issue to configure this plugin into Tutor

### ISSUE THREAD

**Issue by manojkumarhr** [overhangio/tutor-figures#6]
![tutor figure error](https://user-images.githubusercontent.com/7630852/164993297-0476819e-d8d9-4ad0-b304-2e3bb549254d.png)
Hi Support,
I am using Ubuntu 20.04 , Tutor V 13.2.0 and Openedx Maple version i am facing this issue when i am trying to configure this plugin into my Edx. For your refence i have attached screenshot

**Comment by regisb** [comment]
See: https://github.com/overhangio/tutor/issues/651#issuecomment-1108114360
